/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_system;

/**
 *
 * @author ASUS
 */
public class loadingbar extends javax.swing.JFrame {

    /**
     * Creates new form loadingbar
     */
    public loadingbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LoadingValue = new javax.swing.JLabel();
        loadbar = new javax.swing.JProgressBar();
        libraryname = new javax.swing.JLabel();
        imageicon = new javax.swing.JLabel();
        loadText1 = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 102, 153));
        Background.setPreferredSize(new java.awt.Dimension(900, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingValue.setForeground(new java.awt.Color(255, 255, 204));
        LoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LoadingValue.setText("0");
        Background.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 70, -1));

        loadbar.setBackground(new java.awt.Color(255, 255, 255));
        loadbar.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        Background.add(loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 484, 880, 10));

        libraryname.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        libraryname.setForeground(new java.awt.Color(204, 255, 255));
        libraryname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libraryname.setText("Perpustakaan Angkasa");
        Background.add(libraryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 310, 890, -1));

        imageicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/anak anak baca buku.png"))); // NOI18N
        Background.add(imageicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 270));

        loadText1.setForeground(new java.awt.Color(255, 255, 204));
        loadText1.setText("Loading.....");
        Background.add(loadText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 460, -1));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/luke-chesser-pJadQetzTkI-unsplash.jpg"))); // NOI18N
        bgimage.setText("jLabel1");
        Background.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void panggillogin(){
        new loginForm().setVisible(true);
    }
    public void panggilmenu(){
        new menuForm_1().setVisible(true);
    }
    public void panggilcari(){
        new pencarianForm().setVisible(true);
    }
    public void panggilpinjam(){
        new peminjamanForm().setVisible(true);
    }
    public void panggilkembali(){
        new pengembalianForm().setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */ 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        loadingbar ld = new loadingbar();
        ld.setVisible(true);
        
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(50);
                ld.LoadingValue.setText(i+"%");
                
                if(i==25){
                    ld.loadText1.setText("Mohon Tunggu Sebentar.....");
                }
                if(i==50){
                    ld.loadText1.setText("Sedang Menyiapkan.....");
                }
                if(i==75){
                    ld.loadText1.setText("Menjalankan.....");
                }
                if(i==95){
                    ld.loadText1.setText("Membuka Program.....");
                }
                ld.loadbar.setValue(i);
            }
            ld.panggillogin();
            ld.dispose();
        }catch(Exception e){
            
        }
        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel bgimage;
    private javax.swing.JLabel imageicon;
    private javax.swing.JLabel libraryname;
    private javax.swing.JLabel loadText1;
    private javax.swing.JProgressBar loadbar;
    // End of variables declaration//GEN-END:variables
}
