/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library_system;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        signText = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        usrnmText = new javax.swing.JLabel();
        usrnmText1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameInput = new javax.swing.JTextField();
        sandiInput = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/kotak biru tuo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(892, 400));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 230, 2));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user.png"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 510, 500));

        signText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signText.setForeground(new java.awt.Color(0, 102, 153));
        signText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signText.setText("Sign In");
        jPanel1.add(signText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 390, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/luke-chesser-pJadQetzTkI-unsplash.jpg"))); // NOI18N
        bg.setText("jLabel1");
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 0, 900, 500));

        usrnmText.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        usrnmText.setForeground(new java.awt.Color(0, 102, 153));
        usrnmText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usrnmText.setText("Password");
        jPanel1.add(usrnmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 100, -1));

        usrnmText1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        usrnmText1.setForeground(new java.awt.Color(0, 102, 153));
        usrnmText1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usrnmText1.setText("Username");
        jPanel1.add(usrnmText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 130, -1));

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setForeground(new java.awt.Color(0, 51, 102));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 80, 30));

        usernameInput.setBackground(new java.awt.Color(255, 255, 255));
        usernameInput.setForeground(java.awt.SystemColor.controlDkShadow);
        usernameInput.setBorder(null);
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        jPanel1.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 260, 30));

        sandiInput.setBackground(new java.awt.Color(255, 255, 255));
        sandiInput.setForeground(java.awt.SystemColor.controlDkShadow);
        sandiInput.setBorder(null);
        jPanel1.add(sandiInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/kotak biru tuo.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setPreferredSize(new java.awt.Dimension(892, 400));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 230, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loadingbar obj = new loadingbar();
        
        if(usernameInput.getText().equals("Admin")&&
           sandiInput.getText().equals("admin123")){
            obj.panggilmenu();
            this.setVisible(false);
        }else if(usernameInput.getText().equals("Member")&&
           sandiInput.getText().equals("member123")){
            obj.panggilmenu();
            this.setVisible(false);
        }else if(usernameInput.getText().equals("User")&&
           sandiInput.getText().equals("user123")){
            obj.panggilmenu();
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Login Gagal");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField sandiInput;
    private javax.swing.JLabel signText;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usrnmText;
    private javax.swing.JLabel usrnmText1;
    // End of variables declaration//GEN-END:variables
}
